# Generated by Django 5.0.3 on 2024-03-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='level_company',
            field=models.IntegerField(choices=[(1, 'Factory'), (2, 'Distributor'), (3, 'Dealership'), (4, 'Big Retail'), (5, 'Individual Entrepreneur')], verbose_name='Type of Company'),
        ),
    ]
