# Generated by Django 5.0.3 on 2024-04-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_alter_company_provider_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'My Company', 'verbose_name_plural': 'My Companies'},
        ),
    ]
